name: Trigger auto deployment for container-app-imrfoaobqkxiy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-imrfoaobqkxiy-AutoDeployTrigger-7a8d574f-0ee6-463f-8647-e737cdd75e49.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPIMRFOAOBQKXIY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPIMRFOAOBQKXIY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPIMRFOAOBQKXIY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPIMRFOAOBQKXIY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPIMRFOAOBQKXIY_REGISTRY_PASSWORD }}
          containerAppName: container-app-imrfoaobqkxiy
          resourceGroup: appspacesfastapib096b1bf
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


